Repository SWU-MEAL/SWU-MEAL-ANDROID, pull requests merged in 2023-10, with the labels that each got.

#7 [UI] : week swubab ui / #6
  app/build.gradle.kts
  app/src/main/java/com/example/swubab/data/ApiPool.kt
  app/src/main/java/com/example/swubab/presentation/week/WeekSwubabFragment.kt
  app/src/main/res/drawable/selector_weekly_calender.xml
  app/src/main/res/drawable/shape_fill_orange_20_rec.xml
  app/src/main/res/drawable/shape_fill_white_10_rec.xml
  app/src/main/res/drawable/shape_weekly.xml
  app/src/main/res/layout/fragment_week_swubab.xml
  app/src/main/res/layout/view_weekly_calender.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 💟 [UI], 🐈‍⬛ 소현이

#10 [Feat] today menu api
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/swubab/data/ApiPool.kt
  app/src/main/java/com/example/swubab/data/TodaySwubabDto.kt
  app/src/main/java/com/example/swubab/data/api/TodaySwubabApiService.kt
  app/src/main/java/com/example/swubab/presentation/mypage/MyVersionActivity.kt
  app/src/main/java/com/example/swubab/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/example/swubab/presentation/today/BreakfastFragment.kt
  app/src/main/java/com/example/swubab/presentation/today/DinnerFragment.kt
  app/src/main/java/com/example/swubab/presentation/today/LaunchFragment.kt
  app/src/main/java/com/example/swubab/presentation/today/TodaySwubabFragment.kt
  app/src/main/java/com/example/swubab/presentation/today/TodayViewPagerAdapter.kt
  app/src/main/res/drawable/today_swubab_blank.xml
  app/src/main/res/layout/activity_my_version.xml
  app/src/main/res/layout/fragment_breakfast.xml
  app/src/main/res/layout/fragment_dinner.xml
  app/src/main/res/layout/fragment_launch.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_today_swubab.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💟 [UI], 🐕 예림이

#13 Feature/#12 week swubab refactor
  app/src/main/java/com/example/swubab/data/ApiPool.kt
  app/src/main/java/com/example/swubab/data/Extension.kt
  app/src/main/java/com/example/swubab/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/example/swubab/presentation/week/WeekSwubabFragment.kt
  app/src/main/res/drawable/shape_fill_white_rec.xml
  app/src/main/res/layout/fragment_breakfast.xml
  app/src/main/res/layout/fragment_dinner.xml
  app/src/main/res/layout/fragment_launch.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_week_swubab.xml
  app/src/main/res/layout/view_empty.xml
  app/src/main/res/layout/view_weekly_calender.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: ⭐ [FEAT], 💟 [UI],  ♻️ [REFACTOR], 🐈‍⬛ 소현이
